# Generated by Django 3.1 on 2020-09-23 04:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
