# Generated by Django 3.1 on 2020-09-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20200923_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='phone',
            new_name='phon',
        ),
    ]
