# Generated by Django 3.1 on 2020-09-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20200923_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='phon',
            new_name='phone',
        ),
    ]
