# Generated by Django 3.1 on 2020-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20200923_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
